In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [2]:
bookdata = pd.read_csv('/opt/ml/finalproject/book-data/merge_data_re.csv')
songdata = pd.read_csv('/opt/ml/finalproject/kakaomusic/top_tag_20000_song2.csv')

In [3]:
bookdata.head(5)

name           isbn           writer  \
0       어느 날, 내 죽음에 네가 들어왔다  9791191043723   세이카 료겐 저/김윤경 역   
1  오늘 밤, 세계에서 이 사랑이 사라진다 해도  9791191043297  이치조 미사키 저/권영주 역   
2                  수상한 중고상점  9791130689241  미치오 슈스케 저/김은모 역   
3                     인간 실격  9788937461033        다자이 오사무 저   
4                        백광  9791191043617  렌죠 미키히코 저/양윤옥 역   

                                               genre  \
0                    국내도서 > 소설/시/희곡 > 일본소설 > 일본 장편소설   
1    국내도서 > 소설/시/희곡 > 테마소설 > 연애/사랑소설\n  국내도서 > 소설...   
2                    국내도서 > 소설/시/희곡 > 일본소설 > 일본 장편소설   
3                    국내도서 > 소설/시/희곡 > 일본소설 > 일본 장편소설   
4    국내도서 > 소설/시/희곡 > 장르소설 > 추리/미스터리\n  국내도서 > 소설...   

                                      images  \
0  http://image.yes24.com/goods/109144983/XL   
1  http://image.yes24.com/goods/102360203/XL   
2  http://image.yes24.com/goods/108787022/XL   
3    http://image.yes24.com/goods/1387488/XL   
4  http://image.yes24.com/goods/107072836/XL   

                                                 raw  \
0  어느 날, 내 죽음에 네가 들어왔다 ,판타지/SF,봄날엔로맨스,세이카 료겐|김윤경,...   
1  오늘 밤, 세계에서 이 사랑이 사라진다 해도,청춘들에게,봄날엔로맨스,학원물,학원/캠...   
2  수상한 중고상점,문학뉴스레터에소개된책,위로와공감 ,어른이를위한힐링책,치유/힐링,カサ...   
3  인간 실격,북클러버의선택,20세기고전,역사와개인,문학으로보는역사,人間失格, 다자이 ...   
4  백광,추리책방,추리책방_추천사를추천합니다,살인사건,추리/미스터리/스릴러,白光 , 렌...   

                    keywordpick                                     keywords  \
0        소설|일본소설|로맨스|판타지|사랑|인생|                    일본소설 청춘소설 로맨스 판타지 시간여행 사신   
1    일본소설|로맨스소설|연애|청춘 소설|도루|고백|        전격소설대상 일본소설 청춘소설 로맨스소설 선행성기억상실증 조건부연애   
2          위로|상처|미스터리|점장|물건|해결|                              사연 해결 위로 환대 따뜻한   
3  세계고전문학|일본소설|불안|인간본성|직소|데카당스|  세계고전문학 일본고전 일본소설 자전적소설 수기 인간본성 불안 두려움 위선 파멸   
4          소설|미스터리|반전|트릭|고백|진실|                                          NaN   

                                               index  \
0  제1장 죽고 싶어 하는 소녀\n제2장 비눗방울처럼\n제3장 지키지도 못할 약속\n제...   
1  모르는 남자애의, 모르는 여자애\n걸음을 뗀 두 사람\n이 여름은 언제나 한 번\n...   
2  봄, 까치로 만든 다리\n여름, 쓰르라미가 우는 강\n가을, 남쪽 인연\n겨울, 귤...   
3  인간 실격\n- 서문\n- 첫 번째 수기\n- 두 번째 수기\n- 세 번째 수기\n...   
4                                     1 - 11\n옮긴이의 말   

                                                line  \
0  - “곧 죽을 수 있었는데.”\n이치노세는 팔을 붙잡힌 채 삐친 듯이 말했다. 아니...   
1  “너랑 사귀어도 되지만 조건이 세 개 있어.”\n설마 고백을 받아들일 줄은 꿈에도 ...   
2  “영의 무생물 이동의 법칙이라. ‘움직이지 않는 물건이라도 누군가에게 방해가 되는 ...   
3                                                NaN   
4  만세 소리와 아내의 미소로 배웅을 받으며 죽음의 길을 떠났던 전쟁 통의 그날 밤, ...   

                                              review sommelier  \
0  “왜 자꾸 내 자살을 방해하는 걸까?”\n가벼운 마음으로 시작한 자살 방해 작전,\...       NaN   
1  머리는 너를 잊어도, 심장은 너를 잊지 않았어.\n세상에 단 한 번뿐인 하루, 세상...       NaN   
2  손때 묻고 상처받은 물건도 반짝반짝 새것이 되는 곳\n수상한 중고상점에서 벌어지는 ...       NaN   
3                                                NaN       NaN   
4  “이런 작가가 있는데 어떻게 미스터리를 쓸 수 있겠는가!”\n_다나카 요시키(《은하...       NaN   

                                               intro  
0  “나는 네가 살았으면 좋겠어”\n모든 걸 포기하려던 순간, 기적처럼 시작된 사랑에 ...  
1  제26회 전격소설대상 ‘미디어워크스문고상’ 수상작\n총 4,607편의 응모 작품 중...  
2  “비싸게 사서 싸게 팝니다.\n아픈 마음까지도 매입합니다!”\n일본 문학상 그랜드슬...  
3  청춘의 한 시기를 통과 의례처럼 거쳐야 하는 일본 데카당스 문학의 대표작\n\t\t...  
4  “저 아이를 죽여 주세요”\n눈부시게 아찔하고 숨 막히게 매혹적인 치정 미스터리\n...

In [3]:
import torch
from transformers import BertTokenizer, BertModel

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)

import matplotlib.pyplot as plt
# % matplotlib inline

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('klue/bert-base')

In [4]:
text = "임베딩을 시도할 문장이다."
marked_text = "[CLS] " + text + " [SEP]"

# Tokenize our sentence with the BERT tokenizer.
tokenized_text = tokenizer.tokenize(marked_text)

# Print out the tokens.
print(tokenized_text)

['[CLS]', '임', '##베', '##딩', '##을', '시도', '##할', '문장', '##이다', '.', '[SEP]']


In [5]:
# Define a new example sentence with multiple meanings of the word "bank"
text = "배를 타고 여행을 간다." \
       "추석에 먹은 배가 맛있었다."

# Add the special tokens.
marked_text = "[CLS] " + text + " [SEP]"

# Split the sentence into tokens.
tokenized_text = tokenizer.tokenize(marked_text)

# Map the token strings to their vocabulary indeces.
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Display the words with their indeces.
for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

[CLS]             2
배             1,131
##를           2,138
타고           11,532
여행            4,062
##을           2,069
간다            6,429
.                18
추석            6,734
##에           2,170
먹             1,059
##은           2,073
배             1,131
##가           2,116
맛있            4,550
##었           2,359
##다           2,062
.                18
[SEP]             3


In [6]:
# Mark each of the 29 tokens as belonging to sentence "1".
segments_ids = [1] * len(tokenized_text)

print (segments_ids)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [7]:
# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

In [8]:
segments_tensors

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
tokens_tensor

tensor([[   101,   9330,  11513,   9845,  11664,   9565,  88904,   8845,  11903,
            119,   9765,  40958,  10530,   9266,  10892,   9330,  11287,   9254,
         119192,  17706,    119,    102]])

In [9]:
model = BertModel.from_pretrained('klue/bert-base')

Some weights of the model checkpoint at klue/bert-base were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [10]:
# Run the text through BERT, and collect all of the hidden states produced
# from all 12 layers. 
model = BertModel.from_pretrained('klue/bert-base',
                                  output_hidden_states = True, # Whether the model returns all hidden-states.
                                  )
model.eval()
with torch.no_grad():
    outputs = model(tokens_tensor, segments_tensors)

    # Evaluating the model will return a different number of objects based on 
    # how it's  configured in the `from_pretrained` call earlier. In this case, 
    # becase we set `output_hidden_states = True`, the third item will be the 
    # hidden states from all layers. See the documentation for more details:
    # https://huggingface.co/transformers/model_doc/bert.html#bertmodel
    hidden_states = outputs[2]

Some weights of the model checkpoint at klue/bert-base were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [27]:
print ("Number of layers:", len(hidden_states), "  (initial embeddings + 12 BERT layers)")
layer_i = 0

print ("Number of batches:", len(hidden_states[layer_i]))
batch_i = 0

print ("Number of tokens:", len(hidden_states[layer_i][batch_i]))
token_i = 0

print ("Number of hidden units:", len(hidden_states[layer_i][batch_i][token_i]))

Number of layers: 13   (initial embeddings + 12 BERT layers)
Number of batches: 1
Number of tokens: 19
Number of hidden units: 768


In [28]:
len(outputs)

3

In [29]:
# `hidden_states` is a Python list.
print('      Type of hidden_states: ', type(hidden_states))

# Each layer in the list is a torch tensor.
print('Tensor shape for each layer: ', hidden_states[0].size())


      Type of hidden_states:  <class 'tuple'>
Tensor shape for each layer:  torch.Size([1, 19, 768])


In [11]:
# Concatenate the tensors for all layers. We use `stack` here to
# create a new dimension in the tensor.
token_embeddings = torch.stack(hidden_states, dim=0)

token_embeddings.size()

torch.Size([13, 1, 19, 768])

In [12]:
token_embeddings = torch.squeeze(token_embeddings, dim=1)

token_embeddings.size()

torch.Size([13, 19, 768])

In [13]:
# Swap dimensions 0 and 1.
token_embeddings = token_embeddings.permute(1,0,2)

token_embeddings.size()


torch.Size([19, 13, 768])

In [14]:
token_vecs = hidden_states[-2][0]

# Calculate the average of all 36 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)

In [35]:
# sentence_embedding

In [36]:
from scipy.spatial.distance import cosine


In [ ]:
diff_배 = 1 - cosine(token_vecs_sum[10], token_vecs_sum[19])


> # 잘돌아가나???

In [16]:
import re
# ex1 = re.split("[.'\n']",bookdata['intro'][0])
# ex2 = re.sub('\n',bookdata['intro'][0])
# ex1 = bookdata['intro'][0].split("\n")

In [66]:
import re
ex2 = re.sub('\n',bookdata['intro'][0],'')
ex2

''

In [39]:
# !pip install sentence_transformers

In [17]:
import numpy as np
import pandas as pd
from numpy import dot
from numpy.linalg import norm
import urllib.request
from sentence_transformers import SentenceTransformer

In [41]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData.csv", filename="ChatBotData.csv")
train_data = pd.read_csv('ChatBotData.csv')
train_data.head()

Q            A  label
0           12시 땡!   하루가 또 가네요.      0
1      1지망 학교 떨어졌어    위로해 드립니다.      0
2     3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3  3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4          PPL 심하네   눈살이 찌푸려지죠.      0

In [48]:
len(train_data)
train = train_data.loc[:1000]

In [18]:
model = SentenceTransformer('sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens')


In [45]:
from tqdm import tqdm,tqdm_pandas
tqdm_pandas(tqdm())

0it [00:00, ?it/s]


In [49]:
train['embedding'] = train.apply(lambda row: model.encode(row.Q), axis = 1)


/tmp/ipykernel_31669/560203640.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['embedding'] = train.apply(lambda row: model.encode(row.Q), axis = 1)


In [19]:
def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

In [64]:
def return_answer(question):
    embedding = model.encode(question)
    train['score'] = train.apply(lambda x: cos_sim(x['embedding'], embedding), axis=1)
    return train.loc[train['score'].idxmax()]['Q']

In [63]:
return_answer(ex1[0])

/tmp/ipykernel_31669/132280281.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['score'] = train.apply(lambda x: cos_sim(x['embedding'], embedding), axis=1)


'누구나 걱정은 있어요.'

> # 평균

In [20]:
booksample = bookdata.sample(5)
booksample
minisample = booksample[['name','index','intro','review']]
minisample

name                                              index  \
4987     그림동화전집 1  메르헨의 즐거움을 찾아서-고산고정일 … 3\n\n\n\nKHM 001 개구리 왕자 ...   
9738     알렉산드로스 2                                                NaN   
4350     미크로메가스 외  해설 \n\n\n\n지은이에 대해\n\n\n\n미크로메가스 \n\n세상 돌아가는 대...   
4438      프랑스 스케치                                                NaN   
4183  어린왕자 미니북 세트  어린 왕자\n\n작품 해설│어린 왕자와 관계를 맺는 순간 삶의 진정한 가치를 만난다...   

                                                  intro  \
4987  252작품 원전완역 결정판 『그림동화전집』 제1권. 이번 완역결정판에는 그림동화 작...   
9738  위대한 정복자 알렉산드로스의 궤적을 생생하게 복원한 역사소설. 32세 나이에 페르시...   
4350  ■ 이 책은 볼떼르의 5개 작품을 싣고 있습니다. \n\n■ 프랑스어 등의 외래어 ...   
4438  <얼굴 빨개지는 아이>, <자전거를 못 타는 아이>, <파리 스케치>의 작가, 장자...   
4183  순수한 영혼 어린 왕자가 알려주는 삶의 의미!\n\t\t \n\t\n\t\n\t\t...   

                                                 review  
4987  한국 최초 원전완역결정판《그림형제동화전집》출간!\n\n온 가족이 읽는 인류의 소망 ...  
9738  인류 역사상 가장 오묘한 인물, 알렉산드로스의 매력을 극대화한 소설\n\n역사소설이...  
4350  국내 최초 소개\n\n볼테르가 인식하고 있는 인간과, 그 인간이 깃들이고 있는 지구...  
4438                                                NaN  
4183  전 세계인이 가장 사랑한 고전, 영원한 스테디셀러\n\n세상에서 가장 순수한 영혼,...

In [21]:
def return_answer(question):
    embedding = model.encode(question)
    train['score'] = train.apply(lambda x: cos_sim(x['embedding'], embedding), axis=1)
    return train.loc[train['score'].idxmax()]['Q']

In [22]:
minisample_ll = minisample.values.tolist()
# minisample_ll[0]

In [81]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
(a + b)/2


array([2., 3., 4., 5., 6.])

In [94]:
a = model.encode('사랑')
b = model.encode('집착')
print(a[:5])
print(b[:5])
# print((a+b)[:5])
# (a+b)[:5]/2



[-0.07355265  0.2414239   1.7733856   0.21062578  0.18702191]
[ 0.32359794 -0.67105293  1.9204549   0.5807152  -0.24775094]


In [ ]:
minisample[minisample['']]

In [32]:
import numpy as np
import re

embeddings = []
for row in minisample_ll:
    # print(row[2])
    sentence_ll = []
    vector_ll = []
    for column in row:
        if not pd.isna(column):
            temp = re.split("[.'\n']",column)
        # print(temp)
        for i in temp:
            if i != '':
                sentence_ll.append(i)
        # print(sentence_ll)
        vectorsum = 0
        for sentence in sentence_ll:
            vectorsum += model.encode(sentence)
        vectorsum = vectorsum/len(sentence_ll)
    embeddings.append(vectorsum)
            
minisample['embedding'] = embeddings
minisample


/tmp/ipykernel_21172/999957682.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  minisample['embedding'] = embeddings


name                                              index  \
4987     그림동화전집 1  메르헨의 즐거움을 찾아서-고산고정일 … 3\n\n\n\nKHM 001 개구리 왕자 ...   
9738     알렉산드로스 2                                                NaN   
4350     미크로메가스 외  해설 \n\n\n\n지은이에 대해\n\n\n\n미크로메가스 \n\n세상 돌아가는 대...   
4438      프랑스 스케치                                                NaN   
4183  어린왕자 미니북 세트  어린 왕자\n\n작품 해설│어린 왕자와 관계를 맺는 순간 삶의 진정한 가치를 만난다...   

                                                  intro  \
4987  252작품 원전완역 결정판 『그림동화전집』 제1권. 이번 완역결정판에는 그림동화 작...   
9738  위대한 정복자 알렉산드로스의 궤적을 생생하게 복원한 역사소설. 32세 나이에 페르시...   
4350  ■ 이 책은 볼떼르의 5개 작품을 싣고 있습니다. \n\n■ 프랑스어 등의 외래어 ...   
4438  <얼굴 빨개지는 아이>, <자전거를 못 타는 아이>, <파리 스케치>의 작가, 장자...   
4183  순수한 영혼 어린 왕자가 알려주는 삶의 의미!\n\t\t \n\t\n\t\n\t\t...   

                                                 review  \
4987  한국 최초 원전완역결정판《그림형제동화전집》출간!\n\n온 가족이 읽는 인류의 소망 ...   
9738  인류 역사상 가장 오묘한 인물, 알렉산드로스의 매력을 극대화한 소설\n\n역사소설이...   
4350  국내 최초 소개\n\n볼테르가 인식하고 있는 인간과, 그 인간이 깃들이고 있는 지구...   
4438                                                NaN   
4183  전 세계인이 가장 사랑한 고전, 영원한 스테디셀러\n\n세상에서 가장 순수한 영혼,...   

                                              embedding  
4987  [-0.007877264, 0.21996626, 0.8149987, 0.056343...  
9738  [-0.033535894, -0.08539312, 0.7183878, 0.09397...  
4350  [0.017699426, 0.19776164, 0.73945665, 0.009871...  
4438  [-0.44242093, 0.007630398, 0.074327245, 0.0571...  
4183  [-0.15334705, 0.07812645, 0.91287047, 0.037772...

In [34]:
songdata.head(5)
minisong = songdata[['song_id','song_title','playlist_tag','playlist_title']].sample(100)
minisong.head(5)

song_id               song_title  \
11220   582263       When We Were Young   
3163    638658                  Turning   
4022    493420          A Song For You    
11723   600431  UP & DOWN (Feat. Risso)   
18226   603057                  Hwi hwi   

                                            playlist_tag  \
11220  Chill|K팝스타|K팝스타6|K팝스타시즌6|OST|OST모음|OST포함|RnB|b...   
3163   Chill|Pop|RnB|soul|가을|감각|감미로운|감성|겨울|고막여친|그루브|그...   
4022   1970년대|1980년대|70s|70년대|80년대|BTOBTIME|Bar에서|Fee...   
11723  GUITAR|OST|OST모음|happy|가그맨|가을|가을노래|가을송|감성|개그맨|...   
18226  1위|2000년대|2017|2018|4월|5월_3주차|Pop|RnB|Summer|U...   

                                          playlist_title  
11220  일단 한 번 들어봐_한 번 들으면 계속 듣고싶은 팝송|" Good Vibe " 　P...  
3163   듣자마자 나도 모르게 리듬 타게 되는 리드미컬한 감성 POP (상시업뎃)|CLOUD...  
4022   píαnσ pσp, 불안한 우리의 감성 속으로 o ॰ ॰ |R&B/Soul 모음|최...  
11723  빵야빵야 심장을 저격하는 감성 플레이리스트|남자친구에게 불러줄 사랑스러운 노래❤|봄...  
18226  혼자 운동할때 듣기 좋은 노래|2017 뜨거웠던 여름을 함께보낸 음악|숨겨진 주옥같...

In [ ]:
minisong_ll = minisong[['song_title','playlist_title']].values.tolist()

embeddings = []
for row in tqdm(minisong_ll):
    # print(row[2])
    sentence_ll = []
    vector_ll = []
    for column in row:
        if not pd.isna(column):
        # print(row[1].split('|'))
            temp = column.split('|')
        for i in temp:
            sentence_ll.append(i)
    vectorsum = 0
        
    for sentence in sentence_ll:
        vectorsum += model.encode(sentence)
        # print(len(model.encode(sentence)))
        # break
    vectorsum = vectorsum/len(sentence_ll)
    # print(vectorsum[:5])
    # break
    embeddings.append(vectorsum)
            
minisong['embedding'] = embeddings
minisong

    

In [132]:
def return_answer(embedding):
    # embedding = model.encode(question)
    minisong['score'] = minisong.apply(lambda x: cos_sim(x['embedding'], embedding), axis=1)
    return minisong.loc[minisong['score'].idxmax()]['song_id']

In [142]:
for i in range(5):
    a = minisample.iloc[i].embedding
    print(return_answer(a))

393004
393004
403253
443117
620754


In [145]:
a = minisample.iloc[0].embedding
len(a)

768

In [139]:
minisample.iloc[2]

name                                              마크롤 가비에로의 모험
index        제독의 눈\n\n비와 함께 오는 일로나\n\n아름다운 죽음\n\n\n\n해설 | 실...
intro        콜롬비아 대표 시인이자 소설가, 알바로 무티스의 대표작\n\t\t \n\t\n\t\...
review       마술적 사실주의를 현대 인간의 문제와 연결시킨\n\n콜롬비아 최고의 시인이자 소설가...
embedding    [-0.13231757, 0.055866838, 0.76852053, -0.0364...
Name: 7794, dtype: object

In [140]:
songdata[songdata['song_id'] == 403253]

song_id song_title  artist song_genre song_genre_id  album_id  \
17596   403253       안아줄게  스탠딩 에그       인디음악        GN0500   2293169   

                                            playlist_tag  \
17596  2017|20대|4|7월|JAYJE|OST|hem__j|ralalra|standin...   

                                          playlist_title  \
17596  오늘하루지치고힘들었을 나에게 편안하게 잠들게해줄 음악|오늘도 수고했어요 직장인|힘들...   

                                                   lyric  
17596  그런 날이 있지 |눈물이 막 날것 같은 그런 날|걷는 것마저 힘겹다고 느껴질 때 |...

In [35]:
import numpy as np
import torch

device = torch.device('cuda')

minisong_ll = minisong[['song_title','playlist_title']].values.tolist()
minisong_ll = torch.Tensor(minisong_ll)
type(minisong_ll)

ValueError: too many dimensions 'str'

In [43]:
import numpy as np
import torch

device = torch.device('cuda')

minisong_ll = minisong[['song_title','playlist_title']].values.tolist()
# minisong_ll = torch.Tensor(minisong_ll)

model.to(device)

embeddings = []
for row in tqdm(minisong_ll):
    # print(row[2])
    # row = row.to(device)
    sentence_ll = []
    vector_ll = []
    for column in row:
        if not pd.isna(column):
        # print(row[1].split('|'))
            temp = column.split('|')
        for i in temp:
            sentence_ll.append(i)
    vectorsum = np.zeros(768)
    # vectorsums = torch.Tensor(vectorsum)
    # vectorsums = vectorsum.to(device)  

    # sentence_lls = torch.Tensor(vectorsum)
    # sentence_lls.to(device)
    for sentence in sentence_ll:
        vectorsum += model.encode(sentence)
        # print(len(model.encode(sentence)))
        # break
    vectorsum = vectorsum/len(sentence_ll)
    # print(vectorsum[:5])
    # break
    # vectorsum = vectorsum.to('cpu')  

    embeddings.append(vectorsum)
            
minisong['embedding'] = embeddings
minisong

    

100%|██████████| 100/100 [01:51<00:00,  1.12s/it]


song_id                                         song_title  \
11220   582263                                 When We Were Young   
3163    638658                                            Turning   
4022    493420                                    A Song For You    
11723   600431                            UP & DOWN (Feat. Risso)   
18226   603057                                            Hwi hwi   
...        ...                                                ...   
4630    520850        차가운 바람이 불면 (Feat. 모하) (OST Remastered Ver.)   
1500    389099                               Put That A$$ To Work   
2971    411372  Brave Shine (페이트 / 스테이 나이트 `언리미티드 블레이드 워크스` 오프...   
7484    356376                                              새끼손가락   
15249   370760                                             뜨거울 나이   

                                            playlist_tag  \
11220  Chill|K팝스타|K팝스타6|K팝스타시즌6|OST|OST모음|OST포함|RnB|b...   
3163   Chill|Pop|RnB|soul|가을|감각|감미로운|감성|겨울|고막여친|그루브|그...   
4022   1970년대|1980년대|70s|70년대|80년대|BTOBTIME|Bar에서|Fee...   
11723  GUITAR|OST|OST모음|happy|가그맨|가을|가을노래|가을송|감성|개그맨|...   
18226  1위|2000년대|2017|2018|4월|5월_3주차|Pop|RnB|Summer|U...   
...                                                  ...   
4630   JTBC|OST|bgm|가을|가을에|감성|감성적인|개강|고뇌|공감|기분전환|기분좋은...   
1500   2020년걱정노노|8090|Club|EDM|HipHop|HipHop_Rap|Loun...   
2971   ANI|JPOP|JRock|J_POP|OST|One_Ok_Rock|aimer|bgm...   
7484   2017|Apink|감동|감성|걸그룹|걸그룹발라드|겨울|공감|공연|그리움|기분전환|...   
15249  2010|HipHop|RnB|groove|ralalra|가사좋은노래|가요|가을|가을...   

                                          playlist_title  \
11220  일단 한 번 들어봐_한 번 들으면 계속 듣고싶은 팝송|" Good Vibe " 　P...   
3163   듣자마자 나도 모르게 리듬 타게 되는 리드미컬한 감성 POP (상시업뎃)|CLOUD...   
4022   píαnσ pσp, 불안한 우리의 감성 속으로 o ॰ ॰ |R&B/Soul 모음|최...   
11723  빵야빵야 심장을 저격하는 감성 플레이리스트|남자친구에게 불러줄 사랑스러운 노래❤|봄...   
18226  혼자 운동할때 듣기 좋은 노래|2017 뜨거웠던 여름을 함께보낸 음악|숨겨진 주옥같...   
...                                                  ...   
4630   뭔가 위로가 필요해 (들어와요)|독특한 이름으로 기억에 쏙 남는 인디 뮤지션들의 노...   
1500   신나는 음악|『패션매장 전용 리스트-(신남)』|붐.붐.헬스장에서 저절로 바벨 들게될...   
2971   노래찾기 귀찮죠? 일본애니메이션 OP ED OST!|jpop 백과사전ver.3.0|...   
7484   자전거 타면서 들으면 좋은노래|18번째 dj 플레이리스트|혼자서 쉬고 싶은 오후에 ...   
15249  봄이 왔어요❤|¶¶비오는 날에 어울리는 잔잔함을 느끼고 싶다면¶¶|겨울밤엔 발라드와...   

                                               embedding  
11220  [-0.07492465993798361, -0.060990588194349916, ...  
3163   [-0.0237871686528836, -0.17566321450950845, 1....  
4022   [-0.06214346119220583, -0.0028707383272166434,...  
11723  [-0.07990266702730547, -0.03751893747301603, 0...  
18226  [-0.10197250808221191, -0.10877948581164547, 0...  
...                                                  ...  
4630   [-0.16514130487390186, -0.0019215943048829618,...  
1500   [0.0909980779290724, -0.13438542891608576, 1.1...  
2971   [-0.26790784613694996, -0.07789212042310585, 0...  
7484   [-0.14168663209778043, -0.1300926351748211, 0....  
15249  [-0.05214053388058304, -0.12084333769863942, 1...  

[100 rows x 5 columns]

In [44]:
a = minisong[['song_id','embedding']]
a.to_csv('minisong_embedding.csv')

In [ ]:
train['embedding'] = train.apply(lambda row: model.encode(row.Q), axis = 1)
